name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Rename JAR for Deployment
        run: mv target/*.jar target/ddemiral.jar

          # --- NEW STEP: FTP UPLOAD ---
      - name: 🚀 Upload JAR to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
         server: rathgeb.at
         username: f018212f
         password: HTL-Steyr4400
         port: 21
         protocol: ftp
         security: loose
         # Add this to ignore certificate errors if the server uses self-signed certsa
         ignore-ssl-errors: true
         # The local folder where the JAR lives
         local-dir: ./target/
         # Only upload the JAR, ignore the messy Maven folders
         exclude: |
           **/*
           !ddemiral.jar

      # This is the new step to make your JAR downloadableaa
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: java-app-binary
          path: target/*.jar
          retention-days: 5 # Optional: clean up old files after 5 days a

      - name: Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true